version: '2'
services:
  db:
    image: mariadb
    environment:
      MYSQL_DATABASE: name
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
  adminer:
    image: adminer
    ports:
      - "8080:8080"
  redis:
    image: redis
    ports:
      - "6379:6379"
