version: '2'
services:
  db:
    image: mariadb
    environment:
      MYSQL_DATABASE: it_test
      MYSQL_USER: it
      MYSQL_PASSWORD: iamapassword
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  web:
    build:
      context: .
      dockerfile: test.Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - ./app:/app/app
      - ./spec:/app/spec
  adminer:
    image: adminer
    ports:
    - 8080:8080
