development:
  client_credentials: <%= ENV.fetch("CLIENT_CREDENTIALS"){"key"}%>
production:
  client_credentials: <%= ENV.fetch("CLIENT_CREDENTIALS"){"key"}%>
  cthit_slack_url: <%= ENV.fetch("CTHIT_SLACK_URL") {"https://hooks.slack.com"} %>
  mrcit_slack_url: <%= ENV.fetch("MRCIT_SLACK_URL") {"https://hooks.slack.com"} %>
  secret_key_base: <%= ENV.fetch("SECRET_KEY_BASE")%>
