development:
    client_credentials: <%= ENV.fetch("CLIENT_CREDENTIALS") { "key" }%>
production:
    client_credentials: <%= ENV.fetch("CLIENT_CREDENTIALS") { "key" }%>
    slack_url: <%= ENV.fetch("SLACK_URL") { "https://hooks.slack.com" }%>
    secret_key_base: <%= ENV.fetch("SECRET_KEY_BASE")%>

